name: cicd


on:
  push:
    branches: [main]

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@main
        with:
          publish: true
      - run: melos format
