name: Prepare release
on:
  push:
    branches: [main]

jobs:
  create-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@main
        with:
          version: true
          publish-dry-run: true
          create-pr: true
