name: Publish packages
on:
  push:
    branches: [main]


jobs:
 test:
   runs-on: [ ubuntu-latest ]
   if: contains(github.event.head_commit.message, 'chore(release)')
   steps:
     - name: Release packages
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
     - uses: bluefireteam/melos-action@main
       with:
         publish: true

