name: Publish packages
on:
  push:
    tags:
    # This must align with the tag-pattern configured on pub.dev, if you are
    # not in a monorepo you usually just need 'v[0-9]+.[0-9]+.[0-9]+*'.
    # If your repository contains multiple packages consider a pattern like:
    - '[a-z0-9_]+-v[0-9]+.[0-9]+.[0-9]+.*'

jobs:
 publish-packages:
   name: Publish packages
   permissions:
     id-token: write
   runs-on: [ ubuntu-latest ]
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
     - uses: bluefireteam/melos-action@main
       with:
         publish: true

