name: Publish packages
on: workflow_dispatch
  #push:
  #  tags:
  #    - '*-v[0-9]+.[0-9]+.[0-9]+'
  #   #- '[a-z0-9_]+-v[0-9]+.[0-9]+.[0-9]+-[A-Za-z0-9-_]*'

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      id-token: write
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@main
        with:
          publish: true
