name: Publish packages
on:
  push:
    branches: [main]

jobs:
 publish-packages:
   permissions:
     contents: write
   runs-on: [ ubuntu-latest ]
   if: contains(github.event.head_commit.message, 'chore(release)')
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
     - uses: bluefireteam/melos-action@main
       with:
         publish: true

